ACTUAL_CAUSATION_MEASURE: PMI
ASSUME_CUTS_CANNOT_CREATE_NEW_CONCEPTS: false
CACHE_POTENTIAL_PURVIEWS: true
CACHE_REPERTOIRES: true
CES_DISTANCE: SUM_SMALL_PHI
CLEAR_SUBSYSTEM_CACHES_AFTER_COMPUTING_SIA: false
DISTINCTION_PHI_NORMALIZATION: NUM_CONNECTIONS_CUT
IIT_VERSION: 4.0
LOG_FILE: pyphi.log
LOG_FILE_LEVEL: INFO
LOG_STDOUT_LEVEL: WARNING
MAXIMUM_CACHE_MEMORY_PERCENTAGE: 50
MIP_TIE_RESOLUTION:
- NORMALIZED_PHI
- NEGATIVE_PHI
NUMBER_OF_CORES: -1
PARALLEL: true
PARALLEL_COMPLEX_EVALUATION:
  chunksize: 64
  parallel: true
  progress: true
  sequential_threshold: 16
PARALLEL_CONCEPT_EVALUATION:
  chunksize: 256
  parallel: true
  progress: true
  sequential_threshold: 64
PARALLEL_CUT_EVALUATION:
  chunksize: 4096
  parallel: true
  progress: true
  sequential_threshold: 1024
PARALLEL_MECHANISM_PARTITION_EVALUATION:
  chunksize: 4096
  parallel: true
  progress: true
  sequential_threshold: 1024
PARALLEL_PURVIEW_EVALUATION:
  chunksize: 256
  parallel: true
  progress: true
  sequential_threshold: 64
PARALLEL_RELATION_EVALUATION:
  chunksize: 4096
  parallel: true
  progress: true
  sequential_threshold: 1024
PARTITION_TYPE: ALL
PRECISION: 13
PRINT_FRACTIONS: true
PROGRESS_BARS: true
PURVIEW_TIE_RESOLUTION: PHI
RAY_CONFIG: {}
REDIS_CACHE: false
REDIS_CONFIG:
  db: 0
  host: localhost
  port: 6379
  test_db: 1
RELATION_COMPUTATION: CONCRETE
REPERTOIRE_DISTANCE: GENERALIZED_INTRINSIC_DIFFERENCE
REPERTOIRE_DISTANCE_INFORMATION: GENERALIZED_INTRINSIC_DIFFERENCE
REPR_VERBOSITY: 2
SINGLE_MICRO_NODES_WITH_SELFLOOPS_HAVE_PHI: false
STATE_TIE_RESOLUTION: PHI
SYSTEM_CUTS: 3.0_STYLE
SYSTEM_PARTITION_INCLUDE_COMPLETE: false
SYSTEM_PARTITION_TYPE: SET_UNI/BI
VALIDATE_CONDITIONAL_INDEPENDENCE: true
VALIDATE_SUBSYSTEM_STATES: true
WELCOME_OFF: false
